apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: appmon-basic-grafana-instance
  app: appmon-dedalus
metadata:
  annotations:
    description: |-
      Grafana instance definition with ephemeral storage.
      For more information about using this template, including OpenShift considerations, see https://github.com/dedalus-enterprise-architect/grafana-resources/blob/master/README.md.
    iconClass: icon-d4center
    tags: dedalus-grafanaoperator,dedalus
  name: dedalus-grafanaoperator
objects:
# :::
# ::: It creates the Grafana instance with the following features:
# :::   - ephemeral storage
# :::   - basic authentication
# :::
- apiVersion: grafana.integreatly.org/v1beta1
  kind: Grafana
  metadata:
    namespace: ${MONITORING_NAMESPACE}
    name: appmon-basic
    labels:
      app: appmon-dedalus
      dashboards: "appmon-basic"
  spec:
    route:
      spec: {}
    client:
      preferService: "true"
    config:
      log:
        level: warn
        mode: console
      auth.anonymous:
        enabled: "false"
      auth:
        disable_login_form: "false"
        disable_signout_menu: "false"
      auth.basic:
        enabled: "true"
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 200Mi
# :::
# ::: It needed for Grafana Administrator Login getting the credentials from the secret: "grafana-admin-credentials"
# :::
# - apiVersion: route.openshift.io/v1
#   kind: Route
#   metadata:
#     name: grafana-basic-admin
#     labels:
#       app: appmon-dedalus
#   spec:
#     port:
#       targetPort: grafana
#     tls:
#       termination: edge
#       insecureEdgeTerminationPolicy: Redirect
#     to:
#       kind: Service
#       name: grafana-service
parameters:
- name: MONITORING_NAMESPACE
  displayName: Type the Namespace "name"
  description: Namespace "name" that will be created and where all the resources of AppMon will be deployed
  required: true
  value: dedalus-monitoring