apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-grafana-template
metadata:
  annotations:
    description: |-
      Grafana dashboard definition about the JVM without persistent storage.
      For more information about using this template, including OpenShift considerations, see https://github.com/dedalus-enterprise-architect/grafana-resources/blob/master/README.md.
    iconClass: icon-d4center
    tags: dedalus-grafana,dedalus
  name: dedalus-grafana
objects:
- apiVersion: grafana.integreatly.org/v1beta1
  kind: GrafanaDatasource
  metadata:
    name: prometheus-grafana-ds
    labels:
      app: appmon-dedalus
  spec:
    valuesFrom:
      - targetPath: "secureJsonData.httpHeaderValue1"
        valueFrom:
          secretKeyRef:
            name: "appmon-serviceaccount-api-token"
            key: "token"
    instanceSelector:
      matchLabels:
        dashboards: "appmon-basic"
    allowCrossNamespaceImport: true
    datasource:
      access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer ${token}
      type: prometheus
      url: 'https://${PROMETHEUS_URL}'
parameters:
- name: TOKEN_BEARER
  displayName: Openshift Token Bearer
  description: Type the Openshift Token
  required: false
  value:
- name: PROMETHEUS_URL
  displayName: Thanos Querier URL
  description: Type the Thanos querier URL (prometheus-k8s.openshift-monitoring.svc.cluster.local:9091)
  required: true
  value: prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
