kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: thanos-tenancy
  namespace: openshift-monitoring
spec:
  path: /api
  to:
    kind: Service
    name: thanos-querier
    weight: 100
  port:
    targetPort: tenancy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None