apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-grafanaoperator-template
metadata:
  annotations:
    description: |-
      Grafana Operator ClusterRoleBinding needed by grafana-serviceaccount to connect to thanos querier on port 9091
      For more information about using this template, including OpenShift considerations, see https://github.com/dedalus-enterprise-architect/grafana-resources/blob/master/README.md.
    iconClass: icon-d4center
    tags: dedalus-grafanaoperator,dedalus
  name: dedalus-grafanaoperator
objects:
# :::
# ::: Grafana Operator RBAC
# :::
- apiVersion: rbac.authorization.k8s.io/v1 
  kind: ClusterRole 
  metadata:
    name: aggregate-grafana-admin-edit 
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true" 
      rbac.authorization.k8s.io/aggregate-to-edit: "true" 
  rules:
  - apiGroups:
    - "integreatly.org"
    resources:
    - grafanas
    - grafanas/status
    - grafanas/finalizers
    - grafanadashboards
    - grafanadatasources
    - grafanadatasources/status
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"
    - "delete"
    - "deletecollection"
- apiVersion: rbac.authorization.k8s.io/v1 
  kind: ClusterRole
  metadata:
    name: aggregate-grafana-view
    labels:
      rbac.authorization.k8s.io/aggregate-to-view: "true" 
      rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
  rules:
  - apiGroups:
    - "integreatly.org"
    resources:
    - grafanas
    - grafanas/status
    - grafanas/finalizers
    - grafanadashboards
    - grafanadatasources
    - grafanadatasources/status
    verbs:
    - "get"
    - "list"
    - "watch"
# :::
# ::: It needed by the oAuth login - SSO
# :::
- apiVersion: v1
  kind: Secret
  metadata:
    name: grafana-proxy
    labels:
      app: grafana-dedalus
  stringData:
    session_secret: Dedalus_01
  type: Opaque
# :::
# ::: It needed by the oAuth login - SSO
# :::
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      config.openshift.io/inject-trusted-cabundle: "true"
      app: grafana-dedalus
    name: grafana-oauth-certs
  # :::
  # ::: cluster role: create the grafana-proxy role
  # :::
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: grafana-proxy-${NAMESPACE}
    labels:
      app: grafana-dedalus
  rules:
    - verbs:
        - create
      apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
    - verbs:
        - create
      apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
# :::
# ::: It needed by the oAuth login - SSO
# :::
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: grafana-proxy-${NAMESPACE}
    labels:
      app: grafana-dedalus
  subjects:
    - kind: ServiceAccount
      name: grafana-serviceaccount
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: grafana-proxy-${NAMESPACE}
parameters:
- name: NAMESPACE
  displayName: Namespace where the grafana Operator will be installed in
  description: Type the Namespace where the grafana Operator will be installed in
  required: true
  value: dedalus-monitoring