apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app: appmon-dedalus
    template: appmon-openshift-requirements
  name: prometheus-grafana-ds
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    secureJsonData:
      httpHeaderValue1: Bearer ${token}
    type: prometheus
    url: https://{{ .Values.prometheus_url }}
  instanceSelector:
    matchLabels:
      dashboards: {{ .Values.grafana_instance_name }}
  valuesFrom:
  - targetPath: secureJsonData.httpHeaderValue1
    valueFrom:
      secretKeyRef:
        key: token
        name: appmon-serviceaccount-api-token
