apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    app: appmon-dedalus
    dashboards: {{ .Values.grafana_instance_name }}
    template: appmon-openshift-requirements
  name: {{ .Values.grafana_instance_name }}
  namespace: {{ .Values.monitoring_namespace }}
spec:
  client:
    preferIngress: false
  config:
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    auth.anonymous:
      enabled: "false"
    auth.basic:
      enabled: "true"
    log:
      level: warn
      mode: console
  route:
    spec: {}
