apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: appmon-dedalus
    template: appmon-openshift-requirements
  name: {{ .Values.appmon_serviceaccount }}
secrets:
- name: appmon-serviceaccount-api-token
