# 
# This definition is not compliants with Openshift 3.11
# Getting the cluster version:
#   oc get clusterversion -o jsonpath='{.items[].status.desired.version}{"\n"}' | cut -d. -f1,2
# 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ${APP_NAME}
    k8s-app: ${APP_NAME}
  name: ${APP_NAME}-8080-tcp
spec:
  endpoints:
    - interval: 30s
      port: 8080-tcp
      scheme: http
      # HTTP path to scrape for metrics
      path: /metrics
      # tlsConfig:
      #   caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      #   certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      #   keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      #   serverName: oauth-openshift.openshift-authentication.svc
      # jobLabel: component
      # Timeout after which the scrape is ended
      # scrapeTimeout:
      relabelings:
        # - action: replace
        #   regex: (.*)
        #   replacement: $1
        #   separator: ;
        #   sourceLabels:
        #     - __meta_kubernetes_namespace
        #   targetLabel: namespace
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: kubernetes_namespace
  # podTargetLabels:
  #   - kubernetes_namespace
  selector:
    matchLabels:
      app: ${APP_NAME}
  targetLabels:
    - app
