kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-grafana-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas
  - grafanadashboards
  - grafanadatasources
  - grafanafolders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas/status
  - grafanadashboards/status
  - grafanadatasources/status
  - grafanafolders/status
  verbs:
  - get