---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-grafana-admin-edit 
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas
  - grafanadashboards
  - grafanadatasources
  - grafanafolders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas/status
  - grafanadashboards/status
  - grafanadatasources/status
  - grafanafolders/status
  verbs:
  - get
