apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-grafanaoperator-template
metadata:
  annotations:
    description: |-
      Grafana Operator ClusterRoleBinding needed by appmon-serviceaccount to connect to thanos querier on port 9091
      For more information about using this template, including OpenShift considerations, see https://github.com/dedalus-enterprise-architect/grafana-resources/blob/master/README.md.
    iconClass: icon-d4center
    tags: dedalus-grafanaoperator,dedalus
  name: dedalus-grafanaoperator
objects:
# :::
# ::: cluster role binding: give the RBAC cluster-monitoring-view permission to the appmon-serviceaccount
# :::
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: grafana-cluster-monitoring-view-binding
    labels:
      app: grafana-dedalus
  subjects:
    - kind: ServiceAccount
      namespace: ${NAMESPACE}
      name: appmon-serviceaccount
  roleRef:
    kind: ClusterRole
    name: cluster-monitoring-view
    apiGroup: rbac.authorization.k8s.io
parameters:
- name: NAMESPACE
  displayName: Namespace where the grafana Operator will be installed in
  description: Type the Namespace where the grafana Operator will be installed in
  required: true
  value: dedalus-monitoring
