apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-grafanaoperator-template
metadata:
  annotations:
    description: |-
      Grafana Operator definition with persistent storage.
      For more information about using this template, including OpenShift considerations, see https://github.com/dedalus-enterprise-architect/grafana-resources/blob/master/README.md.
    iconClass: icon-d4center
    tags: dedalus-grafanaoperator,dedalus
  name: dedalus-grafanaoperator
objects:
# :::
# ::: It needed by the Grafana Operator object
# :::
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: grafana-operator-group
    labels:
      app: grafana-dedalus
  spec:
    targetNamespaces:
    - ${NAMESPACE}
# :::
# ::: Grafana Operator installation
# :::
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    # annotations:
    #   olm.operatorGroup: grafana-operator-group
    name: grafana-operator
    labels:
      app: grafana-dedalus
    # For AllNamespaces install mode usage, specify the 'openshift-operators' namespace.
    # Otherwise, specify the relevant single namespace for SingleNamespace install mode usage.
    # look for installModes by command: 'oc get packagemanifests grafana-operator -o yaml'
    namespace: ${NAMESPACE}
  spec:
    # Name of the channel to subscribe to.
    # look for the channel version available by command: 'oc get packagemanifests grafana-operator -o yaml'
    channel: v4
    # Set the approval strategy to Manual in case your specified version is superseded by a later version in the catalog.
    # This plan prevents an automatic upgrade to a later version and requires manual approval before the starting CSV can complete the installation.
    installPlanApproval: Manual
    # Name of the Operator to subscribe to
    name: grafana-operator
    # Name of the catalog source that provides the Operator.
    # you can choose among 'redhat-operators' and 'community-operators'
    source: community-operators
    # Namespace of the catalog source. Use openshift-marketplace for the default OperatorHub catalog sources.
    sourceNamespace: openshift-marketplace
    # Set a specific version of an Operator CSV
    startingCSV: grafana-operator.v4.2.0
    config:
      env:
        - name: DASHBOARD_NAMESPACES_ALL
          value: "${DASHBOARD_NAMESPACES_ALL}"
      # envFrom: 
      # - secretRef:
      #     name: license-secret
      # volumes: 
      # - name: <volume_name>
      #   configMap:
      #     name: <configmap_name>
      # volumeMounts: 
      # - mountPath: <directory_name>
      #   name: <volume_name>
      # tolerations: 
      # - operator: "Exists"
      resources: 
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      # The nodeSelector parameter defines a NodeSelector for the pod created by OLM
      # nodeSelector: 
      #   foo: bar
# :::
# ::: Grafana Service Account
# :::
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: appmon-serviceaccount
    labels:
      app: grafana-dedalus
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
parameters:
- name: NAMESPACE
  displayName: Namespace where the grafana Operator will be installed in
  description: Type the Namespace where the grafana Operator will be installed in
  required: true
  value: dedalus-monitoring
- name: DASHBOARD_NAMESPACES_ALL
  displayName: Dashboards Scan
  description: Type to 'true' wheather you want enable the dashboard discovery across all namespaces
  required: true
  value: "true"